# Site settings
title: Shubham Shaswat
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shubham Shaswat
user_description: I\'m a Computer Science Engineer, always searching for the next challenge; I am very passionate about Artificial Intelligence; Always looking for some interesting project to work on and I love contributing to open source
user_title: Software Engineer
email: shaswat.cpp@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
